In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import g_key
gmaps.configure(api_key=g_key)

In [2]:
# import csv file with weather data pulled from open weather api
cities_df = pd.read_csv("Resources/cities_weather.csv")
cities_df = cities_df.dropna()
cities_df.head()

,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,T훮yb훮d,34.7400,60.7756,39.92,61,0,1.54,IR,1611773811
1,Torbay,47.6666,-52.7314,30.00,80,75,13.80,CA,1611773812
2,Talnakh,69.4865,88.3972,-21.23,85,100,4.29,RU,1611773813
3,Saskylakh,71.9167,114.0833,-43.60,79,79,1.66,RU,1611773814
4,Pevek,69.7008,170.3133,-24.68,87,100,3.09,RU,1611773815

In [42]:
# set marker locations and pull humidty rate to display on google map
marker_locations = cities_df[['Latitude', 'Longitude']]
humidity_rate = cities_df['Humidity'].astype(float)
max_intensity = cities_df['Humidity'].max()
# set gmaps configuration with center point and zoom set 
fig = gmaps.figure(center=(0.0, 0.0), zoom_level=2)

# create heat layer to lay on map
heat_layer = gmaps.heatmap_layer(marker_locations, weights=humidity_rate, 
                                 dissipating=False, 
                                 max_intensity=max_intensity.astype(float), 
                                 point_radius=1)
# display map
fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Create data frame with ideal condidtions for vacation spots around the world
ideal_conditions = cities_df[(cities_df['Max Temp'] > 70) & (cities_df['Max Temp'] < 80) \
                             & (cities_df['Cloudiness'] < 25) & (cities_df['Wind Speed'] > 10)]
ideal_conditions.head()

,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
13,Carnarvon,-24.8667,113.6333,71.60,83,0,18.41,AU,1611773825
27,Rikitea,-23.1203,-134.9692,79.32,76,6,14.23,PF,1611773841
74,Atuona,-9.8000,-139.0333,78.22,77,1,16.67,PF,1611773899
95,Nouadhibou,20.9310,-17.0347,71.60,68,0,12.66,MR,1611773925
173,Calama,-22.4667,-68.9333,77.00,13,0,17.27,CL,1611774015

In [34]:
# Create parameters to pull lodging data from google places api
target_radius = 5000
target_type = "lodging"

params = {
    "radius": target_radius,
    "type" : target_type,
    "key" : g_key
}

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
print("Starting Hotel Search")
print("----------------------------------------")
# Loop through ideal conditions locations and pull hotel information for closest spot and
# put into new column of dataframe
for index, row in ideal_conditions.iterrows():
    # add additional parameters for location
    lat = row['Latitude']
    lon = row['Longitude']
    
    params["location"] = f"{lat},{lon}"
    
    print(f"Retrieving Results for: {row['City']}.")
    
    response = requests.get(base_url, params=params).json()
    
    hotels = response['results']
    # use try/except to pull information from api call and add to dataframe
    try:
        print(f"Closest hotel is {hotels[0]['name']}.")
        ideal_conditions.loc[index, 'Hotel Name'] = hotels[0]['name']
    except (KeyError, IndexError):
        print("Missing Results....Skipping")
    print("----------------------------------------")

Starting Hotel Search
----------------------------------------
Retrieving Results for: Carnarvon.
Closest hotel is Hospitality Carnarvon.
----------------------------------------
Retrieving Results for: Rikitea.
Closest hotel is Pension Maro'i.
----------------------------------------
Retrieving Results for: Atuona.
Closest hotel is Villa Enata.
----------------------------------------
Retrieving Results for: Nouadhibou.
Closest hotel is El Medina.
----------------------------------------
Retrieving Results for: Calama.
Closest hotel is Park Hotel Calama.
----------------------------------------
Retrieving Results for: Basco.
Closest hotel is Nathaniel's Lodge.
----------------------------------------
Retrieving Results for: Oddur.
Closest hotel is Banjanay Hotel.
----------------------------------------
Retrieving Results for: Cap-Ha챦tien.
Closest hotel is Habitation Jouissant.
----------------------------------------
Retrieving Results for: Bubaque.
Closest hotel is Casa Dora, Bubaque.
----------------------------------------
Retrieving Results for: Mier.
Closest hotel is Mier 09.
----------------------------------------
Retrieving Results for: Bandarbeyla.
Closest hotel is JABIR HOTEL.
----------------------------------------
Retrieving Results for: Taoudenni.
Missing Results....Skipping
----------------------------------------
Retrieving Results for: Beloha.
Missing Results....Skipping
----------------------------------------
Retrieving Results for: Antofagasta.
Closest hotel is Holiday Inn Express Antofagasta.
----------------------------------------
Retrieving Results for: Moyale.
Closest hotel is La Tahzan Guest House.
----------------------------------------
Retrieving Results for: Ati.
Missing Results....Skipping
----------------------------------------
Retrieving Results for: Marsabit.
Closest hotel is Chicho Hotel.
----------------------------------------
Retrieving Results for: Chicama.
Closest hotel is Hospedaje Punta Cana PERU.
----------------------------------------
Retrieving Results for: T챕nenkou.
Missing Results....Skipping
----------------------------------------

In [35]:
# put combined data into new data frame and drop locations that did not have a hotel within
# outlined parameters
hotel_df = ideal_conditions.dropna()
hotel_df

,City,Latitude,Longitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
13,Carnarvon,-24.8667,113.6333,71.60,83,0,18.41,AU,1611773825,Hospitality Carnarvon
27,Rikitea,-23.1203,-134.9692,79.32,76,6,14.23,PF,1611773841,Pension Maro'i
74,Atuona,-9.8000,-139.0333,78.22,77,1,16.67,PF,1611773899,Villa Enata
95,Nouadhibou,20.9310,-17.0347,71.60,68,0,12.66,MR,1611773925,El Medina
173,Calama,-22.4667,-68.9333,77.00,13,0,17.27,CL,1611774015,Park Hotel Calama
182,Basco,20.4487,121.9702,73.11,78,6,18.88,PH,1611773934,Nathaniel's Lodge
197,Oddur,4.1213,43.8894,79.25,39,0,10.60,SO,1611774054,Banjanay Hotel
200,Cap-Ha챦tien,19.7578,-72.2042,77.43,75,0,14.85,HT,1611773837,Habitation Jouissant
235,Bubaque,11.2833,-15.8333,78.42,66,0,15.41,GW,1611774107,"Casa Dora, Bubaque"
250,Mier,26.4333,-99.1500,73.99,14,1,12.66,MX,1611774128,Mier 09
280,Bandarbeyla,9.4942,50.8122,73.98,73,0,18.59,SO,1611774167,JABIR HOTEL
333,Antofagasta,-23.6500,-70.4000,71.60,64,20,17.27,CL,1611774134,Holiday Inn Express Antofagasta
351,Moyale,3.5167,39.0584,74.61,36,0,12.10,KE,1611774131,La Tahzan Guest House
405,Marsabit,2.3284,37.9899,71.35,50,0,10.29,KE,1611774322,Chicho Hotel
406,Chicama,-7.8447,-79.1469,71.60,78,20,11.50,PE,1611774323,Hospedaje Punta Cana PERU

In [36]:
# create location and markers to display hotel info on map
locations = hotel_df[['Latitude', 'Longitude']]
markers = gmaps.marker_layer(locations)

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# add a layer to the map that displays the info box information with Hotel info.
hotel_layer = gmaps.symbol_layer(locations, fill_color='rgba(0, 180, 0, 0.4)',
    stroke_color='rgba(0, 0, 180, 0.4)', scale=2,
    info_box_content=hotel_info 
                                )
# Display the map with hotel information and markers. 
fig.add_layer(hotel_layer)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))